# Laboratorio de regresión - 3

## Significancia de factores

|                |   |
:----------------|---|
| **Nombre**     | Emiliano Valderrama del Toro  |
| **Fecha**      | 25/08/2025  |
| **Expediente** | 744673|

Descarga el archivo de publicidad y carga los datos (Advertising.csv).

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [76]:
data = pd.read_csv("Advertising.csv")
data.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

**¿Hay alguna relación entre el presupuesto para publicidad y las ventas?**

Nuestra primera meta debe ser determinar si hay evidencia en los datos de que haya una asociación entre estas variables.

- ¿Por qué? ¿Qué resultaría si nos diéramos cuenta de la falta de relación entre el presupuesto de publicidad y las ventas?

**¿Qué tan fuerte es esta relación?**
Asumiendo que existe esta relación, ¿nos sirve conocer el impacto que tiene invertir en publicidad en las ventas?

**¿Cuáles medios están asociados con las ventas? ¿Qué tan grande es la asociación entre un medio específico y las ventas?**

Hay 3 medios distintos en los datos. ¿Sirve invertir en los 3? ¿Conviene más invertir sólo en uno?

**¿Qué tan seguros estamos de que podríamos predecir ventas futuras?**

**¿La relación es lineal?**

**¿Hay sinergia entre estos medios?**

Puede ser que gastar \\$50,000 en publicidad y otros \\$50,000 en radio es mejor opción que gastar \\$100,000 en televisión. A esto le llamamos efecto de interacción.

Podemos usar regresión lineal para responder todas estas preguntas.

Realiza una regresión lineal:

$$ \text{ventas} \approx \beta_0 + (\beta_1)(\text{TV})$$

In [3]:
x = data[['TV']]
y = data[['sales']]
X = x.values.reshape(-1,1)
Y = y.values.reshape(-1,1)

lr = LinearRegression()
lr.fit(X,Y)


LinearRegression()

In [4]:
b0 = lr.intercept_
b0

array([7.03259355])

In [5]:
b1 = lr.coef_
b1

array([[0.04753664]])

In [6]:
y1 = lr.predict(X)

### Verificando la precisión de nuestros coeficientes estimados

Recuerda que en el mundo real hay ruidos y errores de medición. Siempre se asume que la verdadera relación entre $X$ y $Y$ es $$Y = \beta_0 + \beta_1 X + \epsilon$$

Se asume que el término de error es independiente de $X$ (el error siempre es el mismo sin importar el valor de $X$). Este modelo describe a la *línea de regresión de la población*, que es la mejor aproximación de la verdadera relación entre $X$ y $Y$. Cuando usamos mínimos cuadrados encontramos la *línea de mínimos cuadrados*.

¿Cuál es la diferencia entre población y muestra?

¿Cuál crees que sea la diferencia entre hacer una regresión con todos los datos de la población y una muestra de ella?

La línea de regresión de la población no se puede observar. El concepto de comparar estas líneas es una extensión natural del acercamiento estadístico estándar de usar información de una muestra para estimar características de una población grande.

Imagina que quieres encontrar la altura promedio de un mexicano $\mu$. Medir a todos y cada uno de los mexicanos en situaciones similares, con la misma regla, mismo operador, y otras incontables formas de minimizar la variación de la medida es una tarea imposible. Lo que podemos asumir es que $\hat{\mu} = \bar{y}$. La media poblacional y la media muestral son diferentes, pero la media muestral es usualmente un buen estimado.

De la misma manera, como no contamos con el 100% de la información para hacer una regresión, los coeficientes $\beta_0$ y $\beta_1$ son desconocidos. Podemos estimarlos usando mínimos cuadrados, encontrando $\hat{\beta_0}$ y $\hat{\beta_1}$. Puede que las muestras que tengamos en ese momento estén un poco por encima de la media, pero otras muestras en otro momento puede que estén debajo de la media. En general, esperamos que el promedio de las aproximaciones $\hat{\mu}$ aproxime a $\mu$.

Esto lleva a la pregunta: ¿qué tan cercanos son nuestros coeficientes estimados a los verdaderos coeficientes? Utilizamos el concepto de error estándar para evaluar esto.

$$ \text{Var}(\hat{\mu})=\text{SE}(\hat{\mu})^2 = \frac{\sigma^2}{n} $$

Donde $\sigma$ es la desviación estándar de cada una de las observaciones $y_i$ de $Y$. El error estándar nos dice la cantidad promedio que el estimado difiere del valor verdadero. Podemos ver en la fórmula que entre más observaciones tengamos el error se hace más pequeño. Las fórmulas para errores estándar de $\hat{\beta_0}$ y $\hat{\beta_1}$ son:

$$ \text{SE}(\hat{\beta_0})^2 = \sigma^2 [\frac{1}{n} + \frac{\bar{x}^2}{\sum_{i=1}^n (x_i - \bar{x})^2}]$$

$$ \text{SE}(\hat{\beta_1})^2 = \frac{\sigma^2}{\sum_{i=1}^n (x_i - \bar{x})^2}$$

$$ \sigma^2 = \text{Var}(\epsilon) = \text{RSE}^2 = \frac{\text{RSS}}{n-p}$$

Para que estas fórmulas sean validas asumimos que los errores $\epsilon_i$ tienen varianza común $\sigma^2$ y que no están correlacionados.

Calcula los errores estándar de los coeficientes

In [7]:
x_mean = np.mean(X)

In [8]:
n = 200
p = 2

In [9]:
RSS = np.sum((y1 - Y)**2)
des = RSS / (n-p)
des

10.618841328946218

In [11]:
se_b0 = np.sqrt (des * ( (1/n) + ( (x_mean**2) / (np.sum ((X-x_mean)**2)))))
se_b1 = np.sqrt(des / np.sum(((X - x_mean)**2)))

In [12]:
se_b0, se_b1

(0.4578429402734785, 0.0026906071877968707)

Estos errores se pueden usar para calcular intervalos de confianza. Un intervalo de confianza del $95\%$ se define como un rango de valores en el cuál se encuentra el desconocido valor verdadero con un $95\%$ de probabilidad.

Otra forma de verlo es que si tomamos muestras repetidas y construimos un intervalo de confianza para cada una, el $95\%$ de los intervalos creados van a contener el valor verdadero. Para la regresión el intervalo de confianza del $95\%$ toma la forma:

$$ \hat{\beta_j} \pm 2\text{SE}(\hat{\beta_j})$$

Calcula los intervalos de confianza para los coeficientes estimados:

In [13]:
mas_b0 = b0 + 2*se_b0
menos_b0 = b0 - 2*se_b0

mas_b1 = b1 + 2*se_b1
menos_b1 = b1 - 2*se_b1

In [14]:
print(f"{menos_b0} < x < {mas_b0}")
print(f"{menos_b1} < x < {mas_b1}")

[6.11690767] < x < [7.94827943]
[[0.04215543]] < x < [[0.05291785]]


Los errores estándar también se usan para realizar pruebas de hipótesis. La prueba de hipótesis más común es probar la hipótesis nula de:

$$ H_0: \text{No hay relación entre } X \text{ y } Y \ \ \ \ (\beta_1=0)$$

contra la hipótesis alternativa:
$$ H_0: \text{Hay alguna relación entre } X \text{ y } Y \ \ \ (\beta_1 \neq 0)$$

Explica con tus palabras el significado de la hipótesis nula y la hipótesis alternativa.

Para probal la hipótesis nula debemos determinar si nuestro estimado $\hat{\beta_1}$ de $\beta_1$ está lo suficientemente alejado de cero para que podamos decir con confianza que este valor no es cero. 

¿Qué tan lejos? Depende de qué tanta confianza tengamos en el estimado encontrado. Si nuestro error estándar es pequeño y nuestro estimado está alejado de cero podríamos decir que hay muy poca probabilidad de que el valor verdadero sea 0. En cambio, si nuestro error estándar es grande y nuestro estimado está muy cerca de cero, entonces podrías ser que el valor verdadero sea cero y que no haya relación entre las variables.

Se calcula un *estadístico t* dado por
$$ t = \frac{\hat{\beta_j} - \mu}{\text{SE}(\hat{\beta_j})} $$

donde $\mu$ es el valor contra el que queremos probar.

Calcula el estadístico t para tus coeficientes estimados, usando como referencia la prueba de hipótesis.

In [15]:
t_b0 = (b0 - 0) / se_b0
t_b0

array([15.36027517])

In [16]:
t_b1 = (b1 - 0) / se_b1
t_b1

array([[17.6676256]])

La distribución t tiene forma de campana y se parece bastante a la distribución normal cuando $n > 30$. Ya sólo es cuestión de calcular la probabilidad de observar cualquier número tal que su valor absoluto sea igual o mayor que el valor absoluto del estadístico t calculado. En otras palabras:
$$ P(|x| \geq |t|) $$

A esta probabilidad la llamamos *p-value*. Un *p-value* pequeño indica que es poco probable que exista por puro azar una relación significativa entre predictor y respuesta, en caso de que no haya una asociación real entre predictor y respuesta. En otras palabras, el *p-value* te dice la probabilidad de que parezca que hay relación cuando no la hay.

Si el *p-value* es pequeño, inferimos que sí hay una asociación entre el predictor y la respuesta, y **rechazamos la hipótesis nula**.
  

¿Qué tan pequeño? Depende de la aplicación. Un valor muy común es del $5\%$.

Utiliza el siguiente código para calcular el *p-value* para tus coeficientes

`from scipy import stats`

`p_bj = 2*(1 - stats.t.cdf(np.abs(t_bj), n-p))`

In [17]:
from scipy import stats
p_b0 = 2*(1 - stats.t.cdf(np.abs(t_b0), n-p))
p_b0

array([0.])

In [18]:
p_b1 = 2*(1 - stats.t.cdf(np.abs(t_b1), n-p))
p_b1

array([[0.]])

¿Se rechaza la hipótesis nula? ¿Qué significa?

con beta 0 se rechaza y con b1 se acepta. Por lo que 

Realiza otras dos regresiones. Ya tienes hecha la regresión de ventas dado el gasto en publicidad de TV. Realiza la regresión para gastos en radio y gastos en periódico. Organiza las respuestas para que debajo de esta celda se tenga:
- Título de regresión
- Coeficientes estimados
- Errores estándar de los coeficientes
- Intervalos de confianza
- Estadísticos t
- p-values
- Observaciones

## Regresión de ventas dado el gasto de publicidad en periódico

In [77]:
x = data[['newspaper']]
y = data[['sales']]
X = x.values.reshape(-1,1)
Y = y.values.reshape(-1,1)

lr = LinearRegression()
lr.fit(X,Y)

LinearRegression()

In [78]:
# Betas, predicción más promedio de la variable
b0 = lr.intercept_
b1 = lr.coef_
y1 = lr.predict(X)
x_mean = np.mean(X)

### Coeficientes estimados

In [79]:
print(f"El coeficiente de beta_0 es de: {b0} y de beta_1 es de: {b1}")

El coeficiente de beta_0 es de: [12.35140707] y de beta_1 es de: [[0.0546931]]


### Errores de coeficientes

In [49]:
RSS = np.sum((y1 - Y)**2)
des = RSS / (n-p)
se_b0 = np.sqrt (des * ( (1/n) + ( (x_mean**2) / (np.sum ((X-x_mean)**2)))))
se_b1 = np.sqrt(des / np.sum(((X - x_mean)**2)))

In [36]:
print(f"Los errores de los coeficiente son: de beta_0 es de: {se_b0} y de beta_1 es de: {se_b1}")

Los errores de los coeficiente son: de beta_0 es de: 0.6214201876094345 y de beta_1 es de: 0.016575721876358165


### Intervalos de las betas

In [38]:
mas_b0 = b0 + 2*se_b0
menos_b0 = b0 - 2*se_b0

mas_b1 = b1 + 2*se_b1
menos_b1 = b1 - 2*se_b1

print(f" Intervalos de b0 {menos_b0} < x < {mas_b0}")
print(f" Intervalos de b1 {menos_b1} < x < {mas_b1}")

 Intervalos de b0 [11.10856669] < x < [13.59424744]
 Intervalos de b1 [[0.02154165]] < x < [[0.08784454]]


### Estadísticos t

In [40]:
t_b0 = (b0 - 0) / se_b0
t_b1 = (b1 - 0) / se_b1
t_b0, t_b1

(array([19.87609562]), array([[3.29959074]]))

### P_values

In [34]:
from scipy import stats
p_b0 = 2*(1 - stats.t.cdf(np.abs(t_b0), n-p))
p_b1 = 2*(1 - stats.t.cdf(np.abs(t_b1), n-p))
p_b0, p_b1

(array([0.]), array([[0.0011482]]))

## Regresión de ventas dado el gasto de publicidad en radio

In [59]:
x = data[['radio']]
y = data[['sales']]
X = x.values.reshape(-1,1)
Y = y.values.reshape(-1,1)

lr = LinearRegression()
lr.fit(X,Y)

LinearRegression()

In [60]:
# Betas, predicción más promedio de la variable
b0 = lr.intercept_
b1 = lr.coef_
y1 = lr.predict(X)
x_mean = np.mean(X)

### Coeficientes estimados

In [61]:
print(f"El coeficiente de beta_0 es de: {b0} y de beta_1 es de: {b1}")

El coeficiente de beta_0 es de: [9.3116381] y de beta_1 es de: [[0.20249578]]


### Errores de coeficientes

In [62]:
RSS = np.sum((y1 - Y)**2)
des = RSS / (n-p)
se_b0 = np.sqrt (des * ( (1/n) + ( (x_mean**2) / (np.sum ((X-x_mean)**2)))))
se_b1 = np.sqrt(des / np.sum(((X - x_mean)**2)))

In [63]:
print(f"Los errores de los coeficiente son: de beta_0 es de: {se_b0} y de beta_1 es de: {se_b1}")

Los errores de los coeficiente son: de beta_0 es de: 0.5629004962718711 y de beta_1 es de: 0.020411306360090635


### Intervalos de las betas

In [64]:
mas_b0 = b0 + 2*se_b0
menos_b0 = b0 - 2*se_b0

mas_b1 = b1 + 2*se_b1
menos_b1 = b1 - 2*se_b1

print(f" Intervalos de b0 {menos_b0} < x < {mas_b0}")
print(f" Intervalos de b1 {menos_b1} < x < {mas_b1}")

 Intervalos de b0 [8.1858371] < x < [10.43743909]
 Intervalos de b1 [[0.16167317]] < x < [[0.2433184]]


### Estadísticos t

In [65]:
t_b0 = (b0 - 0) / se_b0
t_b1 = (b1 - 0) / se_b1
t_b0, t_b1

(array([16.54224531]), array([[9.92076547]]))

### P_values

In [66]:
from scipy import stats
p_b0 = 2*(1 - stats.t.cdf(np.abs(t_b0), n-p))
p_b1 = 2*(1 - stats.t.cdf(np.abs(t_b1), n-p))
p_b0, p_b1

(array([0.]), array([[0.]]))

## Regresión lineal múltiple

En lugar de hacer una regresión para cada factor independiente, quizás se puede extender el modelo para que tenga varios factores dentro:

$$ Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + ... + \beta_p X_p + \epsilon $$

Para nuestro ejemplo de publicidad:

$$ \text{sales} = \beta_0 + \beta_1 (\text{TV}) + \beta_2 (\text{radio}) + \beta_3 (\text{newspaper}) + \epsilon $$

Utiliza la librería `statsmodels` para realizar la regresión. Por defecto la librería statsmodels no toma en cuenta el intercepto ($\beta_0$), por lo que se tendrá que agregar una columna de unos de tamaño *n* a la matriz X.

`import statsmodels.api as sm`

`ols = sm.OLS(Y, X)`

`results = ols.fit()`

`results.summary()`

In [67]:
import statsmodels.api as sm

In [96]:
x = data[['TV', "radio", "newspaper"]]
y = data[['sales']]

X = sm.add_constant(x)

In [97]:
ols = sm.OLS(y, X)
results = ols.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Thu, 28 Aug 2025   Prob (F-statistic):           1.58e-96
Time:                        17:16:50   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.000       2.324       3.554
TV             0.0458      0.001     32.809      0.000       0.043       0.049
radio          0.1885      0.009     21.893      0.000       0.172       0.206
newspaper     -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [120]:
x_news = data["newspaper"].values.reshape(-1, 1)
x_tv = data["TV"].values.reshape(-1, 1)
x_radio = data["radio"].values.reshape(-1, 1)

In [121]:
x = np.hstack([TV, radio, x_news, x_tv*x_radio, x_tv*x_news, x_radio*x_news])
y = data[['sales']]

X = sm.add_constant(x)

In [122]:
ols = sm.OLS(y, X)
results = ols.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.969
Model:                            OLS   Adj. R-squared:                  0.968
Method:                 Least Squares   F-statistic:                     993.3
Date:                Thu, 28 Aug 2025   Prob (F-statistic):          3.68e-142
Time:                        17:49:03   Log-Likelihood:                -267.49
No. Observations:                 200   AIC:                             549.0
Df Residuals:                     193   BIC:                             572.1
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.4602      0.318     20.342      0.000       5.834       7.087
x1             0.0203      0.002     12.633      0.000       0.017       0.024
x2             0.0229      0.011      2.009      0.046       0.000       0.045
x3             0.0170      0.010      1.691      0.092      -0.003       0.037
x4             0.0011   5.72e-05     19.930      0.000       0.001       0.001
x5         -7.971e-05   3.58e-05     -2.227      0.027      -0.000   -9.12e-06
x6            -0.0001      0.000     -0.464      0.643      -0.001       0.000
==============================================================================
Omnibus:                      111.385   Durbin-Watson:                   2.222
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              767.483
Skew:                          -2.046   Prob(JB):                    2.20e-167
Kurtosis:                      11.681   Cond. No.                     3.80e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.8e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

**¿Qué diferencias puedes observar entre los *p-values* de una regresión múltiple y los encontrados en las regresiones simples? ¿Por qué crees que existen estas diferencias?**

Encontramos que ya una vez haciendo la regresión múltiple los valores que nos arroja de newspaper indican que esta variable ya no es importante, o que ya no está aportando información nueva, puesto que en las demás variables ya se encuentra esa información. Quizá por separado si sea importante, pero ya en conjunto pierde importancia.


## Referencia

James, G., Witten, D., Hastie, T., Tibshirani, R.,, Taylor, J. (2023). An Introduction to Statistical Learning with Applications in Python. Cham: Springer. ISBN: 978-3-031-38746-3

## Addendum

Para calcular los *p-values* de los parámetros sin `statsmodels`:
1. Calcular RSS
2. Calcular RSE
3. `var_beta = np.linalg.inv(X.T @ X) * rse**2` (X con columna de intercepto)
4. `std_beta = np.sqrt(var_beta.diagonal())` El orden de los valores corresponde al orden de los factores en las columnas de la matriz $X$.
5. Calcular *estadístico t*
6. Calcular *p-value*